name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        env:
            GCP_ServiceAccount_Key: ${{ secrets.GCP_ServiceAccount_Key }}
            GCP_ProjectID: ${{ secrets.GCP_ProjectID }}
            GCP_Bucket: conduit-gcs-testing
        run: make test GOTEST_FLAGS="-v -count=1"
